# Oracle Database
spring:
  datasource:
    # Replace with actual Oracle connection details
    url: jdbc:oracle:thin:@//${BD_ORACLE_HOST:localhost}:1522/XEPDB1
    driverClassName: oracle.jdbc.OracleDriver
    username: ${BD_ORACLE_USER:rachid}
    password: ${BD_ORACLE_USER_PASSWORD:EnovaBeit@1993}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none # Changed from 'validate' to 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true # Enable Liquibase for this profile
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  # Kafka
# Spring key is repeated for Kafka config
# (Tooling note: The create_file_with_block will create a new file, not merge. The YAML structure itself should be valid for Spring Boot to merge at runtime)
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
