# Spring
spring:
  application:
    name: infra-inventory
  kafka:
    consumer:
      group-id: inventory-service-group
  profiles:
    active: h2-local
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true # Default is true if liquibase-core is on classpath

# Topic Names
order:
  events:
    topic:
      created: order-created-events
      cancelled: order-cancelled-events
inventory:
  events:
    topic:
      reserved: inventory-reserved-events
      depleted: inventory-depleted-events
