spring:
  datasource:
    # Replace with actual Oracle connection details
    url: jdbc:oracle:thin:@your-oracle-host:1521:your-oracle-sid
    driverClassName: oracle.jdbc.OracleDriver
    username: your_oracle_username
    password: your_oracle_password
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none # Changed from 'validate' to 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true # Enable Liquibase for this profile
    change-log: classpath:/db/changelog/db.changelog-master.yaml # Path to the master changelog
