spring:
  application:
    name: infra-order
  profiles:
    active: h2
  # Kafka
  # Spring key is repeated for Kafka config
  # (Tooling note: The create_file_with_block will create a new file, not merge. The YAML structure itself should be valid for Spring Boot to merge at runtime)
  kafka:
    consumer:
      group-id: inventory-service-group
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092,localhost:9093}
    topics:
      order-created: order-created-events
      order-shipped: order-shipped-events
      order-updated: order-updated-events
      order-cancelled: order-cancelled-events
      inventory-reserved: inventory-reserved-events

server:
  port: 8787
