server:
  port: 8787

spring:
  datasource:
    # Replace with actual Oracle connection details
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    driverClassName: oracle.jdbc.OracleDriver
    username: rachid
    password: EnovaBeit@1993
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none # Changed from 'validate' to 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true # Enable Liquibase for this profile
    change-log: classpath:/db/changelog/db.changelog-master.yaml # Path to the master changelog
