apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-system-pv2
  labels:
    name: order-system-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/order-system-data2