apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.infraOrder }}
  namespace: {{ .Values.namespace }}
data:
  SPRING_PROFILES_ACTIVE: "oracle"
  KAFKA_BROKERS: "kafka-broker1:9092,kafka-broker1:9092"
  BD_ORACLE_HOST: oracle-xe
  APP_USER: rachid