{{- if .Values.infraInventory }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.infraInventory.name }}-config
  labels:
    app: {{ .Values.infraInventory.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # application.properties style data
  # These can override values in the packaged application.properties or set new ones
  # Example: spring.profiles.active: {{ .Values.infraInventory.config.springProfilesActive | default "oracle,kubernetes" }}
  # Example: server.port: {{ .Values.infraInventory.config.serverPort | default "8080" }}

  # If you externalize Kafka topics (good practice):
  # ORDER_EVENTS_TOPIC_CREATED: {{ .Values.kafkaTopics.orderCreated | default "order-created-events" }}
  # ORDER_EVENTS_TOPIC_CANCELLED: {{ .Values.kafkaTopics.orderCancelled | default "order-cancelled-events" }}
  # INVENTORY_EVENTS_TOPIC_RESERVED: {{ .Values.kafkaTopics.inventoryReserved | default "inventory-reserved-events" }}
  # INVENTORY_EVENTS_TOPIC_DEPLETED: {{ .Values.kafkaTopics.inventoryDepleted | default "inventory-depleted-events" }}

  # For now, we assume topics are within application.properties, but they can be moved here
  # and referenced as environment variables in the deployment.
  SPRING_PROFILES_ACTIVE: {{ .Values.infraInventory.config.springProfilesActive | default "oracle,kubernetes" }}
  # Add any other configurations needed from values.yaml
  {{- range $key, $value := .Values.infraInventory.config }}
  {{ $key | upper | replace "." "_" }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
