# spring-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-inventory
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-inventory
  template:
    metadata:
      labels:
        app: infra-inventory
    spec:
      containers:
        - name: infra-inventory
          image: {{ .Values.pods.infraInventory.image  }}
          imagePullPolicy: {{ .Values.pods.infraInventory.imagePullPolicy  }}
          ports:
            - containerPort: {{ .Values.pods.infraInventory.port  }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.pods.infraInventory.port  }}
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.pods.infraInventory.port  }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.pods.infraInventory.port  }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configMap.infraInventory}}
                  key: SPRING_PROFILES_ACTIVE
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraInventory }}
                  key: KAFKA_BROKERS
            - name: BD_ORACLE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraInventory }}
                  key: BD_ORACLE_HOST
            - name: BD_ORACLE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraInventory }}
                  key: APP_USER
            - name: BD_ORACLE_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.infraOrder }}
                  key: APP_USER_PASSWORD
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraInventory }}
                  key: CONFIG_SERVER_URL
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraInventory }}
                  key: EUREKA_SERVER_URL

