apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker2
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker2
  template:
    metadata:
      labels:
        app: kafka-broker2
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configMap.kafkaCluster}}
                  key: KAFKA_BROKER_ID_BROKER2
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configMap.kafkaCluster}}
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configMap.kafkaCluster}}
                  key: KAFKA_ADVERTISED_LISTENERS_BROKER2
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configMap.kafkaCluster}}
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR