# spring-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-notification
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-notification
  template:
    metadata:
      labels:
        app: infra-notification
    spec:
      containers:
        - name: infra-notification
          image: {{ .Values.pods.infraNotification.image  }}
          imagePullPolicy: {{ .Values.pods.infraNotification.imagePullPolicy  }}
          ports:
            - containerPort: {{ .Values.pods.infraNotification.port  }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.pods.infraNotification.port  }}
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.pods.infraNotification.port  }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.pods.infraNotification.port  }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraNotification }}
                  key: KAFKA_BROKERS
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraNotification }}
                  key: CONFIG_SERVER_URL
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.infraNotification }}
                  key: EUREKA_SERVER_URL

