apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-system-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.pods.infraOrder.hostIngress  }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infra-order
                port:
                  number: 80