apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-system-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: order-dev.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infra-order
                port:
                  number: 80