apiVersion: v1
kind: Service
metadata:
  name: oracle-xe
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: oracle-xe
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
  type: ClusterIP
