apiVersion: v1
kind: Service
metadata:
  name: infra-order
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: infra-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8787
  type: ClusterIP