apiVersion: v1
kind: Service
metadata:
  name: infra-order
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: infra-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.pods.infraOrder.port  }}
  type: ClusterIP