apiVersion: v1
kind: Service
metadata:
  name: infra-inventory
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: infra-inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.pods.infraInventory.port  }}
  type: ClusterIP