# Spring
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092,localhost:9093}
    consumer:
      group-id: notification-service-group

# Topic Names

order:
  events:
    topic:
      created: order-created-events
      shipped: order-shipped-events
      cancelled: order-cancelled-events
inventory:
  events:
    topic:
      reserved: inventory-reserved-events
      depleted: inventory-depleted-events

server:
  port: 9090
