export enum ActionType {
  NONE = 'NONE',
  OPEN_PANEL = 'OPEN_PANEL',
  CLOSE_PANEL = 'CLOSE_PANEL',
  VIEW_ORDER = 'VIEW_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  CREATE_ORDER = 'CREATE_ORDER',
  CREATE_INVENTORY = 'CREATE_INVENTORY',
  DELETE_INVENTORY = 'DELETE_INVENTORY',
  VIEW_INVENTORY = 'VIEW_INVENTORY'

}


export interface ActionEvent<T> {
  type: ActionType;
  payload?: T;
}