apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-system-pvc
  namespace: infra-order-dev
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: order-system-pv
  storageClassName: ""