-- Liquibase SQL Changelog

-- Create orders table
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(255),
    order_date TIMESTAMP,
    customer_id NUMBER,
    status VARCHAR2(50)
);

-- Create order_items table
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    quantity INT,
    price DECIMAL(19, 2),
    order_id NUMBER NOT NULL
);

-- Add foreign key constraint from order_items to orders
ALTER TABLE order_items
ADD CONSTRAINT fk_order_items_order_id
FOREIGN KEY (order_id)
REFERENCES orders(id);
