-- Liquibase SQL Changelog

-- Create outbox table
CREATE TABLE outbox (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR2(255) NOT NULL,
    aggregate_type VARCHAR2(255) NOT NULL,
    event_type VARCHAR2(255) NOT NULL,
    payload CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at   TIMESTAMP NULL,
    STATUS     VARCHAR2(20)
);
