apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-xe
  template:
    metadata:
      labels:
        app: oracle-xe
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - "mkdir -p /opt/oracle/oradata && chown -R 54321:54321 /opt/oracle/oradata"
          volumeMounts:
            - name: oracle-volume
              mountPath: /opt/oracle/oradata

      containers:
        - name: oracle-xe
          image: gvenzl/oracle-xe
          ports:
            - containerPort: 1521
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "echo 'SELECT 1 FROM DUAL' | sqlplus -s SYSTEM/${ORACLE_PASSWORD}@localhost:1521/XEPDB1"
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 5

          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.bdOracle }}
                  key: ORACLE_PASSWORD

            - name: APP_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.bdOracle }}
                  key: APP_USER

            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.bdOracle }}
                  key: APP_USER_PASSWORD

          volumeMounts:
            - name: oracle-volume
              mountPath: /opt/oracle/oradata

      volumes:
        - name: oracle-volume
          persistentVolumeClaim:
            claimName: order-system-pvc
