apiVersion: v1
kind: Service
metadata:
  name: oracle-xe2
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: oracle-xe2
  ports:
    - name: oracle
      port: 1521          # Port que tu exposes dans le cluster
      targetPort: 1521     # Port utilisé dans le container
  type: ClusterIP

