import { Component, EventEmitter, inject, OnInit, Output } from '@angular/core';
import { AbstractControl, FormArray, FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { getFormControlErrorText } from 'src/app/shared/utils/form-error.util';
import { LogService } from 'src/app/core/services/log.service';
import { InventoryUiFacade } from '../../services/inventory.ui.facade';
import { Inventory } from '../../models/inventory.model';
import { BaseComponent } from '../../../shared/interfaces/index.interface';

@Component({
  selector: 'app-create-item',
  templateUrl: './create-item.component.html',
  styleUrls: ['./create-item.component.scss'],
})
export class CreateItemComponent implements BaseComponent, OnInit {
  private formBuilder: FormBuilder = inject(FormBuilder);
  private inventoryUiFacade: InventoryUiFacade = inject(InventoryUiFacade);
  private logService: LogService = inject(LogService);

  createItemForm!: FormGroup;
  personalInfoForm!: FormGroup;
  loginInfoForm!: FormGroup;
  inventoryItemsForm!: FormArray;

  @Output() eventClose = new EventEmitter<void>();

  ngOnInit(): void {
    this.initFormControls();
    this.initCreateItemForm();
  }

  private initCreateItemForm = (): void => {
    this.createItemForm = this.formBuilder.group({
      personalInfo: this.personalInfoForm,
      loginInfo: this.loginInfoForm,
      items: this.inventoryItemsForm,
    });
  };

  private initFormControls = (): void => {
    this.personalInfoForm = this.formBuilder.group({
      prenom: this.formBuilder.control('', [Validators.required]),
      nom: this.formBuilder.control('', [Validators.required]),
      ville: this.formBuilder.control('', [Validators.required]),
      nationalite: this.formBuilder.control('', [Validators.required]),
      email: this.formBuilder.control('', [Validators.required, Validators.email]),
      phone: this.formBuilder.control('', [Validators.required]),
    });

    this.loginInfoForm = this.formBuilder.group({
      username: this.formBuilder.control('', [Validators.required]),
      password: this.formBuilder.control('', [Validators.required]),
    });

    this.inventoryItemsForm = this.formBuilder.array([]);
  };

  public addInventoryItem(): void {
    this.inventoryItemsForm.push(this.createInventoryItemGroup() as FormGroup);
  }

  public removeInventoryItem(index: number): void {
    this.inventoryItemsForm.removeAt(index);
  }

  public getInventoryItemFormGroup(index: number): FormGroup {
    return this.inventoryItemsForm.at(index) as FormGroup;
  }

  private createInventoryItemGroup(): FormGroup {
    return this.formBuilder.group({
      productId: [null, Validators.required],
      quantity: [1, [Validators.required, Validators.min(1)]],
      price: [0, [Validators.required, Validators.min(0)]],
    });
  }

  onSubmitForm() {
    this.createItemForm.markAllAsTouched();
    if (this.createItemForm.invalid) {
      return;
    }
    const newItem: Inventory = this.mapFormToInventory(this.createItemForm);
    this.logService.debug('newItem :', newItem);
    this.inventoryUiFacade.saveItem(newItem);
    this.createItemForm.reset();
    this.eventClose.emit();
  }

  getErrorMessage(ctrl: AbstractControl): string {
    return getFormControlErrorText(ctrl);
  }

  onClose() {
    this.eventClose.emit();
  }

  private mapFormToInventory = (form: FormGroup): Inventory => {
    const formValue = form.value;
    return {
      itemNumber: '', // Will be generated by the backend
      itemDate: new Date().toISOString(),
      firstName: formValue.personalInfo.prenom,
      lastName: formValue.personalInfo.nom,
      city: formValue.personalInfo.ville,
      nationality: formValue.personalInfo.nationalite,
      email: formValue.personalInfo.email,
      phone: formValue.personalInfo.phone,
      userName: formValue.loginInfo.username,
      password: formValue.loginInfo.password,
      items: formValue.items,
    };
  }
}
